CHANGES.txt, oterm/app/prompt.py
=> Use key binding (ctrl+n) to switch from single to multi-line input.

oterm/ollama.py
=> Handle connection errors in to Ollama.

CHANGES.txt, oterm/__init__.py, oterm/app/image_browser.py, oterm/app/model_selection.py, oterm/app/oterm.py, oterm/app/prompt.py, oterm/app/widgets/chat.py, oterm/app/widgets/image.py, oterm/app/widgets/markdown.py, oterm/app/widgets/prompt.py, oterm/app/widgets/text_area.py, oterm/cli/oterm.py, oterm/config.py, oterm/ollama.py, oterm/store/store.py, oterm/utils.py, tests/test_store.py
We now save the theme to a json file.
This closes #23.
=> Introduce app config stored as json file.

CHANGES.txt, oterm/config.py, pyproject.toml
=> Fix oterm crashing when run for the first time.

CHANGES.txt, oterm/app/image_browser.py, oterm/app/oterm.tcss
=> Allow changing the root of the DirectoryTree in ImageSelect.

CHANGES.txt, README.md, oterm/app/widgets/chat.py, oterm/app/widgets/prompt.py
It is now possible to cancel inference by pressing `ESC`.
=> Ability to cancel inference.

README.md, oterm/cli/oterm.py, oterm/config.py
=> Use 127.0.0.1 instead of 0.0.0.0

CHANGES.txt, pyproject.toml, src/oterm/app/oterm.py
=> Restore shortcut for command palette.

CHANGES.txt, pyproject.toml, src/oterm/app/chat_export.py, src/oterm/app/widgets/chat.py, src/oterm/store/chat.py, src/oterm/store/setup.py, src/oterm/store/store.py, src/oterm/store/upgrades/__init__.py, src/oterm/store/upgrades/v0_5_1.py
Adding ids to messages allows us to reference individual messages making it easy to support things like:
* Message regeneration 
* Message editing
=> Add (id) to message table and adapt store.

README.md, src/oterm/app/oterm.py, src/oterm/app/oterm.tcss, src/oterm/app/pull_model.py, src/oterm/app/widgets/chat.py, src/oterm/ollamaclient.py, tests/conftest.py, tests/test_ollama_api.py
=> Pull models from Ollama.

README.md
Added Sections to the readme to include a table of contents, Ollama installation Guide, and an Update Guide.
Added descriptions to the screenshots.
=> Documentation Update (README File)

CHANGES.txt, README.md, pyproject.toml, src/oterm/app/oterm.py, src/oterm/app/oterm.tcss, src/oterm/config.py, uv.lock
Allows to select among the following predefined themes:
* textual-dark
* textual-light
* nord
* gruvbox
* catppuccin-mocha
* dracula
* tokyo-night
* monokai
* flexoki
* catppuccin-latte
* solarised-light
=> Theme selection.

CHANGES.txt, pyproject.toml, src/oterm/app/oterm.tcss, uv.lock
=> Fix for styling bug that obscured the chat tabs.

CHANGES.txt, README.md, pyproject.toml, src/oterm/app/chat_edit.py, src/oterm/app/oterm.py, src/oterm/app/widgets/chat.py, src/oterm/ollamaclient.py, src/oterm/store/store.py
Use the `format` parameter to specify the output format as a JSON schema.
=> Support "Structured Output"

CHANGES.txt, README.md, pyproject.toml, screenshots/mcp.svg, src/oterm/app/oterm.py, src/oterm/app/widgets/chat.py, src/oterm/ollamaclient.py, src/oterm/tools/__init__.py, src/oterm/tools/mcp.py, uv.lock
[Model Context Protocol](https://github.com/modelcontextprotocol) is an open protocol to connect LLMs with external tools & resources. 
In the PR we aim to convert tools and resources to Ollama tools and give Ollama access to MCP [servers](https://github.com/modelcontextprotocol/servers).
=> Support Model Context Protocol

CHANGES.txt, pyproject.toml, src/oterm/ollamaclient.py, uv.lock
=> Fix passing options to ollama client. 

CHANGES.txt, src/oterm/app/chat_edit.py
=> Patch models that erroneously have single strings as stop words instead of list of strings.

CHANGES.txt, src/oterm/tools/mcp.py
=> Include the user env when running an MCP server with custom env.

README.md, docs/app_config.md, docs/index.md, docs/mcp/index.md
@ggozad I made several minor changes to the documentation after finding issues during my first time using oterm.
Update documentation for Model Context Protocol support to make it friendly for new users.
- update the title
- link the `app_config.md`
- update the note for tool support https://github.com/ggozad/oterm/issues/214
Update README.md with `uv` case and screenshot path
=> Update documentation for Model Context Protocol support

CHANGES.txt, docs/mcp/index.md, src/oterm/ollamaclient.py, src/oterm/tools/mcp/client.py, src/oterm/tools/mcp/sampling.py, tests/tools/mcp_servers.py, tests/tools/test_mcp_sampling.py, tests/tools/test_mcp_tools.py
=> MCP Sampling support

README.md, docs/installation.md
Hey @DanielChesters and @gaelj !
Wanted to add an attribution to your work as package maintainers. 
Does this (see diff) look ok?
Gaël please also check that the command for installing is the right one, qwen2.5-coder told me so ;)
=> Attribution for oterm package maintainers.

CHANGES.txt, src/oterm/app/mcp_prompt.py
=> Allow submission of prompts when they have no fields.

docs/installation.md
Hi there,
I've updated the installation.md to include x install from the x-cmd ecosystem, making oterm installation easier across different platforms and package managers.
I've also created an introduction page:
👉 https://x-cmd.com/install/oterm
Hope this helps! Let me know if any changes are needed.
Thanks!
=> Added x install Support for oterm
